apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rate-limiter
  template:
    metadata:
      labels:
        app: rate-limiter
    spec:
      containers:
        - name: rate-limiter
          image: zebramaschine/rate-limiter:v1
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent 
---
apiVersion: v1
kind: Service
metadata:
  name: rate-limiter
spec:
  type: NodePort
  selector:
    app: rate-limiter
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
